name: Metrics

on:
  schedule: [{ cron: "0 4 * * *" }]
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Token per leggere i dati (API)
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Rome
          config_display: large

          plugin_languages: yes
          plugin_languages_ignored: html, css, markdown, mdx, tex, dockerfile, shell
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 6
          plugin_languages_indepth: no
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

          plugin_habits: no

      - name: Remove links from SVG
        run: |
          test -f github-metrics.svg
          sed -i 's/<a[^>]*>//g; s#</a>##g' github-metrics.svg

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add github-metrics.svg
          git diff --cached --quiet && exit 0

          git commit -m "chore: update metrics"
          git push
